#!/usr/bin/env bash

BUILD_CONFIGURATION=${BUILD_CONFIGURATION:-Release}
DOTNET_VERSION=${DOTNET_VERSION:?DOTNET_VERSION is required, e.g. 6.0 or 8.0}
DOTNET_FRAMEWORK=${DOTNET_FRAMEWORK:-net${DOTNET_VERSION}}

if [[ -n "${DOTNET_PATH:-}" ]]; then
    DOTNET="${DOTNET_PATH}"
elif [[ -n "${DOTNET:-}" ]]; then
    DOTNET="${DOTNET}"
else
    DOTNET=dotnet
fi

export PROJECT_ROOT
export BUILD_CONFIGURATION
export DOTNET_VERSION
export DOTNET_FRAMEWORK
export DOTNET

echo "BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}"
echo "DOTNET_VERSION: ${DOTNET_VERSION}"
echo "DOTNET_FRAMEWORK: ${DOTNET_FRAMEWORK}"
echo "Detected dotnet:"
"${DOTNET}" --info
