agents:
  queue: "default-{queue}"


label: "{name} ({slug})"
key: "build-{slug}"

timeout_in_minutes: 20

commands:
  - echo "+++ Build"
  - bash scripts/cicd/10.build.sh
  - echo "+++ Start Services"
  - bash scripts/tests/setup/start-services.sh
  - echo "+++ Test"
  - bash scripts/cicd/20.test.sh
  - echo "+++ Package"
  - bash scripts/cicd/30.package.sh

plugins:
  - bureau14/qdb-artifacts#master:
      download:
        clean: true
        projects:
          - project_id: "quasardb-build"
            output-dir: "qdb/bin"
            extract: true
            files:
              - "*-server.tar.zst!bin/*"
              - "*-utils.tar.zst!bin/*"
          - project_id: "quasardb-build"
            output-dir: "resolved-on-pipeline-run"
            extract: true
            files:
              - "resolved-on-pipeline-run"
      upload:
        files:
          - "nuget-pack-out/*.nupkg"
          - "Quasardb.Documentation/**/Help/**/*"
          - "Quasardb.Documentation/**/*.chm"
          - "Quasardb.Documentation/**/*.zip"
        base_dir: "."
      promote: {}
  - bureau14/qdb-test-report#master:
      title: "Test report {slug}"
      job:
        variant: {slug}
        junit_input_path: "test-results/junit/*.xml"
